services:
  slides:
    build:
      context: .
    restart: always
    develop:
      watch:
        - action: rebuild
          path: package.json
        - action: sync
          path: .
          target: /slides
    ports:
      - "8101:8101"
      - "35729:35729"
