name: Deploy slides

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
      - name: Install dependencies (apt)
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: pdf2svg fonts-inconsolata
      - name: Install TeX Live
        uses: teatimeguest/setup-texlive-action@v2
        with:
          package-file: tl_packages.txt
      - name: Install dependencies (npm)
        run: npm install --omit=dev
      - name: Compile LaTeX
        run: npm run compile_latex
      - name: Publish
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          exclude_assets: "README.md,dockerfile,.github,.gitignore,.npmignore,gulpfile.js,package.json,package-lock.json,tl_packages.txt,**/*.tex"
          publish_dir: .
          destination_dir: .
